### ISSUE TITLE
Meta: Repository with example testcases

### ISSUE THREAD

**Issue by sgraf812** [dnlkrgr/hsreduce#4]
So that people (including me) can try things out and see how interestingness tests look like.

**Comment by dnlkrgr** [comment]
See https://github.com/dnlkrgr/hsreduce-test-cases.

Example Usage
`hsreduce <path-to-testcase-dir> interesting.sh Bug.hs`

Tickets still to add / fix:

- 8763
- 14827: interestingness test does not give reliable output
- 15164
- 15176
- 15753: can't be printed properly with GHC API
- 18018
- 18098
- 18140
